// Code generated by hero.
// source: github.com/og/juice/example/basic/template/home.html
// DO NOT EDIT!
package template

import (
	"bytes"

	"github.com/shiyanhui/hero"

	IUserService "github.com/og/juice/example/basic/user/interface"

	jhttp "github.com/og/juice/http"
)

func Home(helper jhttp.Helper, userInfo IUserService.UserInfo, list []string, buffer *bytes.Buffer) {
	buffer.WriteString(`
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
   <p>`)
	hero.EscapeHTML(userInfo.Name, buffer)
	hero.FormatInt(int64(userInfo.Age), buffer)
	buffer.WriteString(`</p>
   <ol>
       `)
	for _, s := range list {
		buffer.WriteString(`
       <li>`)
		hero.EscapeHTML(s, buffer)
		buffer.WriteString(`</li>
       `)
	}
	buffer.WriteString(`
   </ol>
    <pre>`)
	hero.EscapeHTML(helper.JSON(list), buffer)
	buffer.WriteString(`</pre>
</body>
</html>`)

}
